'Average selected column values
'INPUTPAYLOAD="TELEMETRYFILE,COLUMN_IDX,"
SVERSION="1.0"
'''''''''''''''''''''''''''''''''''
DEF TOKENIZE(GDZIE, TO_SPLIT )   
  CUR_STRING = ""
  FOR ICT = 0 TO LEN(TO_SPLIT)-1
    LET CHARV = MID( TO_SPLIT, ICT , 1 )
    IF CHARV <> "," THEN 
      CUR_STRING = CUR_STRING + CHARV 
    ELSE  
      PUSH(GDZIE,CUR_STRING)
      CUR_STRING = "" 
    ENDIF
  NEXT ICT 
ENDDEF 
DEF PTOKENIZER( TO_SPLIT , ARG)  
IDX = 0 
CUR_STRING = ""
FOR ICT = 0 TO LEN(TO_SPLIT)-1
  LET CHARV = MID( TO_SPLIT, ICT , 1 )
  IF CHARV <> "," THEN 
    CUR_STRING = CUR_STRING + CHARV 
  ELSE  
    IF IDX = ARG THEN
      RETURN CUR_STRING
    ENDIF
    CUR_STRING = "" 
    IDX = IDX + 1
  ENDIF
NEXT ICT 
ENDDEF  
''''''''''''''''''''''''''''''''''' 
' Find me a \n and return byte number
DEF FINDNEWLINEPOS(STRINGUS)
  FOR ICT = 0 TO LEN(STRINGUS)-1
    CHAR = ASC(MID(STRINGUS,ICT,1))
    IF CHAR = 10 THEN 
      RETURN ICT
    ENDIF
  NEXT ICT
  RETURN -1
ENDDEF  
'''''''''''''''''''''''''''''''''''  
LISTA = LIST()   
STRIN = ""
OUTPUTPAYLOAD = ""
CURSOR = 0
CHUNKSIZE = 128 
VTOTAL = 0
VTOTALCOUNT = 0
''''''''''''''''''''''''''''''''''' 
FNAME$ = PTOKENIZER(INPUTPAYLOAD,0) ' Filename to parse
vVALUE = PTOKENIZER(INPUTPAYLOAD,1) ' Which column to average
VALUEPOSITION = VAL(vVALUE)
 
PRINT "DOWNLOADING ",FNAME$;
GETIT = DOWNLOAD(FNAME$)
PRINT "DOWNLOADED ",GETIT," BYTES"; 

READTIMES = GETIT / CHUNKSIZE
FOR Z = 0 TO READTIMES 
  
  CURSOR = Z * CHUNKSIZE 
  NEWS =  READ(CURSOR,CHUNKSIZE) 

  IF NEWS = "" THEN
  EXIT
  ENDIF

  STRIN = STRIN + NEWS     
  WHILE TRUE
    NEWLINEPOS  = FINDNEWLINEPOS(STRIN)  
    IF NEWLINEPOS < 0 THEN
    EXIT
    ENDIF

    TOKENIZED   = LEFT(STRIN,NEWLINEPOS)
    TOKENIZED   = TOKENIZED +"," 

    CLEAR(LISTA)
    TOKENIZE(LISTA, TOKENIZED)  
    VAR RAWVALUE = GET(LISTA,VALUEPOSITION)  
    VTOTAL = VTOTAL+VAL(RAWVALUE)
    VTOTALCOUNT = VTOTALCOUNT + 1
 
    VAR THESIZE = LEN(STRIN) - NEWLINEPOS  
 
    IF THESIZE < 2 THEN 
      EXIT
    ELSE
      STRIN       = MID(STRIN,NEWLINEPOS + 1,THESIZE - 1)  
    ENDIF
  WEND    
NEXT Z 

VRESULT = VTOTAL/VTOTALCOUNT
OUTPUTPAYLOAD=STR(VRESULT)
