'Average selected column values
'INPUTPAYLOAD="file,col_number,"
'''''''''''''''''''''''''''''''''''
DEF PTOKENIZER( TO_SPLIT , ARG)  
IDX = 0 
CUR_STRING = ""
FOR ICT = 0 TO LEN(TO_SPLIT)-1
CHARV =MID( TO_SPLIT, ICT , 1 )
IF CHARV <> "," THEN 
CUR_STRING = CUR_STRING + CHARV 
ELSE  
IF IDX = ARG THEN
RETURN CUR_STRING
ENDIF
CUR_STRING = "" 
IDX = IDX + 1
ENDIF
NEXT ICT 
ENDDEF  
DEF TOKENIZE(GDZIE, TO_SPLIT )   
  CUR_STRING = ""
  FOR ICT = 0 TO LEN(TO_SPLIT)-1
    LET CHARV = MID( TO_SPLIT, ICT , 1 )
    IF CHARV <> "," THEN 
      CUR_STRING = CUR_STRING + CHARV 
    ELSE  
      PUSH(GDZIE,CUR_STRING)
      CUR_STRING = "" 
    ENDIF
  NEXT ICT 
ENDDEF 
'''''''''''''''''''''''''''''''''''  
TUCURSOR = 0
LISTA = LIST()   
''''''''''''''''''''''''''''''''''' 
DEF READ_UNTIL(ASC_CHARACTER)
STRO=""
WHILE TRUE
    NEWS = READ(TUCURSOR,1)
    '' END
    IF NEWS = "" THEN
    RETURN ""
    ENDIF
    '' NEW LINE
    IF ASC(NEWS) = ASC_CHARACTER THEN
        TUCURSOR = TUCURSOR + 1
        RETURN STRO
    ELSE 
        STRO = STRO + NEWS
    ENDIF
    TUCURSOR=TUCURSOR+1
WEND  
ENDDEF
FNAME$ = PTOKENIZER(INPUTPAYLOAD,0) ' Filename to parse
vVALUE = PTOKENIZER(INPUTPAYLOAD,1) ' Which column to average
VALUEPOSITION = VAL(vVALUE)
  
PRINT "DOWNLOADING ",FNAME$;
GETIT = DOWNLOAD(FNAME$)
PRINT "DOWNLOADED ",GETIT," BYTES"; 
 


VTOTAL = 0
VTOTALCOUNT = 0

WHILE TRUE
 LINE = READ_UNTIL(10)
 IF LINE<>"" THEN
  PRINT LINE;

  CLEAR(LISTA)
  TOKENIZE(LISTA, LINE)  
  VAR RAWVALUE = GET(LISTA,VALUEPOSITION)  
  VTOTAL = VTOTAL+VAL(RAWVALUE)
  VTOTALCOUNT = VTOTALCOUNT + 1

 ELSE
  EXIT
 ENDIF
WEND

VRESULT = VTOTAL/VTOTALCOUNT
OUTPUTPAYLOAD=STR(VRESULT)
 

