''Simple Moving Average
''Dataset File: EPOCH,CLOSING_PRICE,
OUTPUTPAYLOAD = ""
CURS = 0
CSZ = 64 
BUF = "" 
LIST_PRICE=LIST()
LIST_SMA=LIST()

DEF DO_SMA(LISTA,PERIOD) 
	SUM = 0
	SMA = 0
	LLEN=LEN(LISTA)-1
	FOR I = 0 TO LLEN 
		SUM = SUM + GET(LISTA,I)
		IF I >= PERIOD - 1 THEN
			SMA = SUM / PERIOD
			PUSH(LIST_SMA,SMA) 
			SUM = SUM - GET(LISTA,I-(PERIOD-1))
		ELSE
			PUSH(LIST_SMA,0)
		ENDIF
	NEXT I 
ENDDEF
DEF TOK(WHR,TSP)
    CLEAR(WHR)
	CRS=""
	SLEN=LEN(TSP)-1
	FOR ICT=0 TO SLEN
	CHARV=MID(TSP,ICT,1)
	IF CHARV<>"," THEN
	CRS=CRS+CHARV
	ELSE
	PUSH(WHR,CRS)
	CRS=""
	ENDIF
	NEXT ICT
ENDDEF 
DEF FNL(STRS)
    SLEN = LEN(STRS) - 1
    FOR ICT = 0 TO SLEN
        CCC = MID(STRS, ICT, 1)
        IF ASC(CCC) = 10 THEN RETURN ICT
    NEXT ICT
    RETURN -1
ENDDEF 
DEF RLN(FLEN)
    NLN = ""
    NBF = ""
    IF CURS+CSZ > FLEN THEN CSZ = FLEN - CURS
    IF LEN(BUF) < CSZ THEN
        NBF = READ(CURS, CSZ)
        CURS = CURS + LEN(NBF)  
    ENDIF
    IF NBF <> "" THEN BUF = BUF + NBF
    POS = FNL(BUF)
    IF POS <> -1 THEN
        NLN = LEFT(BUF, POS)
        BUF = RIGHT(BUF, LEN(BUF) - POS - 1)
    ELSEIF CURS >= FLEN THEN
        NLN = BUF
        BUF = ""
    ENDIF
    RETURN NLN
ENDDEF 

PAYLOAD=LIST() 
TOK(PAYLOAD,INPUTPAYLOAD)
FNAM = GET(PAYLOAD,0)
PERIOD = VAL(GET(PAYLOAD,1))

GETIT = DOWNLOAD(FNAM)
IF GETIT <= 0 THEN EXIT 

LAL=LIST()
WHILE TRUE
    LINE = RLN(GETIT)
    IF LINE = "" OR CURS >= GETIT THEN EXIT	
	TOK(LAL,LINE)
	EPOCH=GET(LAL,0)
	PUSH(LIST_EPOCH,EPOCH)
	VVV=GET(LAL,1)
	PUSH(LIST_PRICE,VAL(VVV))	
    PRINT ">", EPOCH;
WEND

DO_SMA(LIST_PRICE,PERIOD)
CLEAR(LIST_PRICE)

FOR I = 0 TO LEN(LIST_SMA) - 1
V = GET(LIST_SMA,I)
OUTPUTPAYLOAD=OUTPUTPAYLOAD+STR(V)+CHR(10)
NEXT I 