''Exponential Moving Average
''Dataset File: EPOCH,CLOSING_PRICE,
OUTPUTPAYLOAD = ""
CURS = 0
CSZ = 64 
BUF = "" 
LIST_PRICE=LIST() 
LIST_EMA=LIST() 

DEF DO_EMA(LISTA, PERIOD)
    MULTIPLIER = 2.0 / (PERIOD + 1.0)
    EMA = 0
    FIRST_EMA = 1
    LLEN = LEN(LISTA) -1
    FOR I = 0 TO LLEN
        PRICE = GET(LISTA, I)
        IF FIRST_EMA = 1 AND I >= PERIOD - 1 THEN
            SUM = 0
            FOR J = I - PERIOD + 1 TO I
                SUM = SUM + GET(LISTA, J)
            NEXT J
            EMA = SUM / PERIOD
            FIRST_EMA = 0
        ELSEIF FIRST_EMA = 0 THEN
            EMA = (PRICE * MULTIPLIER) + (EMA * (1 - MULTIPLIER))
        ENDIF
        PUSH(LIST_EMA, EMA)
    NEXT I
ENDDEF

DEF TOK(WHR,TSP)
    CLEAR(WHR)
	CRS=""
	SLEN=LEN(TSP)-1
	FOR ICT=0 TO SLEN
	CHARV=MID(TSP,ICT,1)
	IF CHARV<>"," THEN
	CRS=CRS+CHARV
	ELSE
	PUSH(WHR,CRS)
	CRS=""
	ENDIF
	NEXT ICT
ENDDEF 
DEF FNL(STRS)
    SLEN = LEN(STRS) - 1
    FOR ICT = 0 TO SLEN
        CCC = MID(STRS, ICT, 1)
        IF ASC(CCC) = 10 THEN RETURN ICT
    NEXT ICT
    RETURN -1
ENDDEF 
DEF RLN(FLEN)
    NLN = ""
    NBF = ""
    IF CURS+CSZ > FLEN THEN CSZ = FLEN - CURS
    IF LEN(BUF) < CSZ THEN
        NBF = READ(CURS, CSZ)
        CURS = CURS + LEN(NBF)  
    ENDIF
    IF NBF <> "" THEN BUF = BUF + NBF
    POS = FNL(BUF)
    IF POS <> -1 THEN
        NLN = LEFT(BUF, POS)
        BUF = RIGHT(BUF, LEN(BUF) - POS - 1)
    ELSEIF CURS >= FLEN THEN
        NLN = BUF
        BUF = ""
    ENDIF
    RETURN NLN
ENDDEF 

PAYLOAD=LIST() 
TOK(PAYLOAD,INPUTPAYLOAD)
FNAM = GET(PAYLOAD,0)
PERIOD = VAL(GET(PAYLOAD,1))

GETIT = DOWNLOAD(FNAM)
IF GETIT <= 0 THEN EXIT 

LAL=LIST()
WHILE TRUE
    LINE = RLN(GETIT)
    IF LINE = "" OR CURS >= GETIT THEN EXIT	
	TOK(LAL,LINE)
	EPOCH=GET(LAL,0)	
	VVV=GET(LAL,1)
	PUSH(LIST_PRICE,VAL(VVV))	
    PRINT ">", EPOCH;
WEND

DO_EMA(LIST_PRICE,PERIOD)
CLEAR(LIST_PRICE)

FOR I = 0 TO LEN(LIST_EMA) - 1
PRINT GET(LIST_EMA,I);
NEXT I

OUTPUTPAYLOAD="OK"