'Run kalman filter on a column index
SVERSION="1.3"
PRINT "STARTING ",SVERSION," NOW";
'''''''''''''''''''''''''''''''''''
DEF TOKENIZE(GDZIE, TO_SPLIT )   
  CUR_STRING = ""
  FOR ICT = 0 TO LEN(TO_SPLIT)-1
    LET CHARV = MID( TO_SPLIT, ICT , 1 )
    IF CHARV <> "," THEN 
      CUR_STRING = CUR_STRING + CHARV 
    ELSE  
      PUSH(GDZIE,CUR_STRING)
      CUR_STRING = "" 
    ENDIF
  NEXT ICT 
ENDDEF 
DEF PTOKENIZER( TO_SPLIT , ARG)  
IDX = 0 
CUR_STRING = ""
FOR ICT = 0 TO LEN(TO_SPLIT)-1
  LET CHARV = MID( TO_SPLIT, ICT , 1 )
  IF CHARV <> "," THEN 
    CUR_STRING = CUR_STRING + CHARV 
  ELSE  
    IF IDX = ARG THEN
      RETURN CUR_STRING
    ENDIF
    CUR_STRING = "" 
    IDX = IDX + 1
  ENDIF
NEXT ICT 
ENDDEF  
''''''''''''''''''''''''''''''''''' 
' Find me a \n and return byte number
DEF FINDNEWLINEPOS(STRINGUS)
  FOR ICT = 0 TO LEN(STRINGUS)-1
    CHAR = ASC(MID(STRINGUS,ICT,1))
    IF CHAR = 10 THEN 
      RETURN ICT
    ENDIF
  NEXT ICT
  RETURN -1
ENDDEF  
'''''''''''''''''''''''''''''''''''  
LISTA = LIST()   
STRIN = ""
OUTPUTPAYLOAD = ""
CURSOR = 0
CHUNKSIZE = 128 
''''''''''''''''''''''''''''''''''' 
x = 0
P = 1
Q = 1
R = 1
DEF KalmanUpdate(z)
K = P / (P + R)
x = x + K * (z - x)
P = (1 - K) * P
ENDDEF
''''''''''''''''''''''''''''''''''' 
FNAME$ = PTOKENIZER(INPUTPAYLOAD,0) ' Filename to parse
qQ = PTOKENIZER(INPUTPAYLOAD,1) ' KalmanQ
rR = PTOKENIZER(INPUTPAYLOAD,2) ' KalmanR
vVALUE = PTOKENIZER(INPUTPAYLOAD,3) ' Which column to filter
Q = VAL(qQ)
R = VAL(rR)
VALUEPOSITION = VAL(vVALUE)
 
PRINT "DOWNLOADING ",FNAME$;
GETIT = DOWNLOAD(FNAME$)
PRINT "DOWNLOADED ",GETIT," BYTES"; 

READTIMES = GETIT / CHUNKSIZE
FOR Z = 0 TO READTIMES 
  
  CURSOR = Z * CHUNKSIZE 
  NEWS =  READ(CURSOR,CHUNKSIZE) 


  IF NEWS = "" THEN
  EXIT
  ENDIF

  STRIN = STRIN + NEWS     
  WHILE TRUE
    NEWLINEPOS  = FINDNEWLINEPOS(STRIN)  
    IF NEWLINEPOS < 0 THEN
    EXIT
    ENDIF
    TOKENIZED   = LEFT(STRIN,NEWLINEPOS)
    TOKENIZED   = TOKENIZED +"," 

    CLEAR(LISTA)
    TOKENIZE(LISTA, TOKENIZED)  
    VAR RAWVALUE = GET(LISTA,VALUEPOSITION)  

    ' Kalman
    KalmanUpdate(VAL(RAWVALUE)) 
    OUTPUTPAYLOAD = OUTPUTPAYLOAD + STR(x) + CHR(10) 


    VAR THESIZE = LEN(STRIN) - NEWLINEPOS  
 
    IF THESIZE < 2 THEN 
      EXIT
    ELSE
      STRIN       = MID(STRIN,NEWLINEPOS + 1,THESIZE - 1)  
    ENDIF
  WEND    
NEXT Z 
