DIM HRC(24)
DIM PM1S(24)
DIM PM25S(24)
DIM PM10S(24)
DIM HUS(24)
DIM TMS(24) 
STRIN=""
CURS=0
TCT=0
CURS=0
IJP=0
CSZ=64
LAL=LIST()
BUF=""
LISTA=LIST() 
DEF MAX(a,b)
IF a>b THEN RETURN a
RETURN b
ENDDEF 
DEF PM2IJP(A,B)
R=MAX(A/60,B/100)*5
RETURN R
ENDDEF 
DEF TOK(WHR,TSP)
CRS=""
SLEN=LEN(TSP)-1
FOR ICT=0 TO SLEN
CHARV=MID(TSP,ICT,1)
IF CHARV<>"," THEN
CRS=CRS+CHARV
ELSE
PUSH(WHR,CRS)
CRS=""
ENDIF
NEXT ICT
ENDDEF 
DEF FNL(STRS)
SLEN=LEN(STRS)-1
FOR ICT=0 TO SLEN
CCC=MID(STRS,ICT,1)
IF ASC(CCC)=10 THEN RETURN ICT
NEXT ICT
RETURN -1
ENDDEF 
DEF RLN(FLEN)
NLN=""
NBF=""
IF LEN(BUF)<CSZ THEN
NBF=READ(CURS,CSZ)
CURS=CURS+CSZ
ENDIF
IF CURS+CSZ>FLEN THEN CSZ=FLEN-CURS
IF NBF<>"" THEN
BUF=BUF+NBF
ENDIF
POS=FNL(BUF)
IF POS<>-1 THEN
NLN=LEFT(BUF,POS-1)
ZO=LEN(BUF)-POS-1
IF ZO>0 THEN
BUF=RIGHT(BUF,ZO)
ELSE
BUF=""
ENDIF
ENDIF
RETURN NLN
ENDDEF 
FNAM=INPUTPAYLOAD
GETIT=DOWNLOAD(FNAM)
IF GETIT <= 0 THEN EXIT 
WHILE TRUE
LINE=RLN(GETIT)
IF LINE="" THEN EXIT
CLEAR(LAL)
LINE=LINE+","
TOK(LAL,LINE)
EPOCH=GET(LAL,0)
HR=GET(LAL,1)
PM1=GET(LAL,3)
PM25=GET(LAL,4)
PM10=GET(LAL,5)
HUMI=GET(LAL,6)
TEMP=GET(LAL,7)
GOD=VAL(HR) 
HRC(GOD)=HRC(GOD)+1
PM1S(GOD)=PM1S(GOD)+VAL(PM1)
PM25S(GOD)=PM25S(GOD)+VAL(PM25)
PM10S(GOD)=PM10S(GOD)+VAL(PM10)
HUS(GOD)=HUS(GOD)+VAL(HUMI)
TMS(GOD)=TMS(GOD)+VAL(TEMP)
WEND 
IJP=0
FOR I=0 TO 23
IF HRC(I)>0 THEN
P1A=PM1S(I)/HRC(I)
P25A=PM25S(I)/HRC(I)
P10A=PM10S(I)/HRC(I)
HA=HUS(I)/HRC(I)
TA=TMS(I)/HRC(I)
IJP=PM2IJP(P25A,P10A)
ENDIF
NEXT I 
IJP=FLOOR(IJP)
OUTPUTPAYLOAD="{"+CHR(34)+"IJP"+CHR(34)+": "+STR(IJP)+"}"