OUTPUTPAYLOAD=""
LINE_AS_LIST = LIST()
LIST_RAW_EPOCH=LIST() 

LIST_RAW_PM1=LIST() 
LIST_RAW_PM25=LIST() 
LIST_RAW_PM10=LIST() 

LIST_SMA_PM1=LIST() 
LIST_SMA_PM25=LIST() 
LIST_SMA_PM10=LIST() 


DEF DO_SMA(LISTA,PERIOD,TARGET) 
	SUM = 0
	SMA = 0
	LLEN=LEN(LISTA)-1
	FOR I = 0 TO LLEN 
		SUM = SUM + GET(LISTA,I)
		IF I >= PERIOD - 1 THEN
			SMA = SUM / PERIOD
			PUSH(TARGET,SMA) 
			SUM = SUM - GET(LISTA,I-(PERIOD-1))
		ELSE
			PUSH(TARGET,0)
		ENDIF
	NEXT I 
ENDDEF
DEF TOK(WHR,TSP)
    CLEAR(WHR)
	CRS=""
	SLEN=LEN(TSP)-1
	FOR ICT=0 TO SLEN
	CHARV=MID(TSP,ICT,1)
	IF CHARV<>"," THEN
	CRS=CRS+CHARV
	ELSE
	PUSH(WHR,CRS)
	CRS=""
	ENDIF
	NEXT ICT
ENDDEF 

DEF READF(ASCII)
STRO=""
WHILE TRUE
	NEWS=READ(TCR,1)
	IF NEWS="" THEN
	RETURN ""
	ENDIF
	IF ASC(NEWS)=ASCII THEN
	TCR=TCR+1
	RETURN STRO
	ELSE 
	STRO=STRO+NEWS
	ENDIF
	TCR=TCR+1
WEND
ENDDEF

PAYLOAD=LIST() 
TOK(PAYLOAD,INPUTPAYLOAD)
FNAM = GET(PAYLOAD,0)
PERIOD = VAL(GET(PAYLOAD,1))

GETIT = DOWNLOAD(FNAM)
IF GETIT <= 0 THEN EXIT 

WHILE TRUE
	LINE=READF(10)

	IF LINE<>"" THEN

		LAL=LIST()	
		TOK(LAL,LINE)
		EPOCH=GET(LAL,0)	   
		PM1=GET(LAL,1);
		PM25=GET(LAL,2);
		PM10=GET(LAL,3);
		NEWEPOCH=VAL(EPOCH)+PERIOD*1800
		PUSH(LIST_RAW_EPOCH,NEWEPOCH)
		PUSH(LIST_RAW_PM1,VAL(PM1))
		PUSH(LIST_RAW_PM25,VAL(PM25))
		PUSH(LIST_RAW_PM10,VAL(PM10))
		PRINT LINE,",",NEWEPOCH;


	ELSE
		EXIT
	ENDIF
WEND

DO_SMA(LIST_RAW_PM1,PERIOD,LIST_SMA_PM1)
DO_SMA(LIST_RAW_PM25,PERIOD,LIST_SMA_PM25)
DO_SMA(LIST_RAW_PM10,PERIOD,LIST_SMA_PM10)
CLEAR(LIST_RAW_PM1)
CLEAR(LIST_RAW_PM25)
CLEAR(LIST_RAW_PM10) 


FOR I = 0 TO LEN(LIST_SMA_PM1) - 1
EPOCH = GET(LIST_RAW_EPOCH,I)
PM1 = GET(LIST_SMA_PM1,I)
PM25= GET(LIST_SMA_PM25,I)
PM10= GET(LIST_SMA_PM10,I) 
OUTPUTPAYLOAD=OUTPUTPAYLOAD + STR(EPOCH) + "," + STR(PM1) + "," + STR(PM25) + "," + STR(PM10) + CHR(10)
NEXT I