DOWNLOAD(INPUTPAYLOAD)
SRND(1911)
DEF SIGMOID(X) 
RETURN 1.0/(1.0+EXP(-X))
ENDDEF
DEF DSIGMOID(X) 
RETURN X*(1.0-X)  
ENDDEF
DEF VTOK(SSTR,ARG)  
IDX=0 
CUR_STRING=""
LENN=LEN(SSTR)-1
FOR ICT=0 TO LENN
CHARV=MID(SSTR,ICT,1)
IF CHARV <> "," THEN 
CUR_STRING=CUR_STRING+CHARV 
ELSE  
IF IDX=ARG THEN 
RETURN VAL(CUR_STRING)
ENDIF
CUR_STRING="" 
IDX=IDX+1
ENDIF
NEXT ICT 
ENDDEF 
TUCURSOR=0
DEF READ_UNTIL(ASC_CHARACTER)
STRO=""
WHILE TRUE
NEWS=READ(TUCURSOR,1)
IF NEWS="" THEN RETURN ""
IF ASC(NEWS)=ASC_CHARACTER THEN
TUCURSOR=TUCURSOR+1
RETURN STRO
ELSE 
STRO=STRO+NEWS
ENDIF
TUCURSOR=TUCURSOR+1
WEND  
ENDDEF 
TERROR=0 
LINE=READ_UNTIL(10)  
IIN=VTOK(LINE,0))
IHID=VTOK(LINE,1)
IOUT=VTOK(LINE,2)
IEPO=VTOK(LINE,3)
LRATE=VTOK(LINE,4)
LINE=READ_UNTIL(10)
INUMT=VTOK(LINE,0)
DIM TRIN(INUMT,IIN) 
DIM TROUT(INUMT,IOUT)
DCTR=0
WHILE TRUE
LINE=READ_UNTIL(10)
IF LINE<>"" THEN  
FOR K=0 TO IIN-1
TRIN(DCTR,K)=VTOK(LINE,K)
NEXT K
FOR J=0 TO IOUT-1
TROUT(DCTR,J)=VTOK(LINE,IIN-1+J)
NEXT J
DCTR=DCTR+1  
ELSE
EXIT
ENDIF
WEND
DIM HLYR(IHID)
DIM OLYR(IOUT)
DIM HLYRBIAS(IHID)
DIM OLYRBIAS(IOUT) 
DIM HW(IIN,IHID)
DIM OW(IHID,IOUT)
FOR I=0 TO IIN-1 
FOR J=0 TO IHID-1
HW(I,J)=RND
NEXT J
NEXT I
FOR I=0 TO IHID-1
HLYRBIAS(I)=RND
FOR J=0 TO IOUT-1
OW(I,J)=RND
NEXT J
NEXT I
FOR I=0 TO IOUT-1
OLYRBIAS(I)=RND
NEXT I
FOR N=0 TO IEPO-1
EPOCH_ERROR=0
FOR I=0 TO DCTR-1  
FOR J=0 TO IHID-1
ACT=HLYRBIAS(J)
FOR K=0 TO IIN-1 
ACT=ACT+(TRIN(I,K) *HW(K,J) )
NEXT K
HLYR(J)=SIGMOID(ACT)
NEXT J
FOR J=0 TO IOUT-1
ACT=OLYRBIAS(J)
FOR K=0 TO IHID-1
ACT=ACT+(HLYR(K) *OW(K,J))
NEXT K
OLYR(J)=SIGMOID(ACT)
NEXT J  
DIM DLTOU(IOUT)
FOR J=0 TO IOUT-1
ERROU=TROUT(I,J)-OLYR(J)
DLTOU(J)=ERROU *DSIGMOID(OLYR(J))
EPOCH_ERROR=EPOCH_ERROR+(ERROU *ERROU)
NEXT J
DIM DLTHID(IHID)
FOR J=0 TO IHID-1
ERRHID=0.0f
FOR K=0 TO IOUT-1
ERRHID=DLTOU(K) *OW(J,K)
NEXT K
DLTHID(J)=ERRHID *DSIGMOID(HLYR(J))
NEXT J
FOR J=0 TO IOUT-1
OLYRBIAS(J)=OLYRBIAS(J)+(DLTOU(J) *LRATE)
FOR K=0 TO IHID-1 
OW(K,J)=OW(K,J)+(HLYR(K) *DLTOU(J) *LRATE)
NEXT K
NEXT J
FOR J=0 TO IHID-1
HLYRBIAS(J)=HLYRBIAS(J)+(DLTHID(J) *LRATE)
FOR K=0 TO IIN-1
HW(K,J)=HW(K,J)+(TRIN(I,K) *DLTHID(J) *LRATE)
NEXT K
NEXT J
NEXT I
TERROR=EPOCH_ERROR/(DCTR-1)
PRINT "Epoch ", N, "-Total Error: ", TERROR;
NEXT N   
OUTPUTPAYLOAD="DONE,"+STR(TERROR)+"," 