SRND(1911)
AERR=0.0
TCNT=0
SLINE=""
LLINE=""
LNLS=LIST()
AGV=LIST()
AGV=CSV2LIST(INPUTPAYLOAD)
IIN=VAL(GET(AGV,0))
IHID=VAL(GET(AGV,1))
IOUT=VAL(GET(AGV,2))
IEPO=VAL(GET(AGV,3))
LRATE=VAL(GET(AGV,4))  
FFP=GET(AGV,5)
SAT=VAL(GET(AGV,6))
LCT=VAL(GET(AGV,7))
DIM TTI(IIN)
DIM TTO(IOUT)
DIM HHL(IHID)
DIM OOL(IOUT)
DIM HHLBIAS(IHID)
DIM OOLBIAS(IOUT) 
DIM HHW(IIN,IHID)
DIM OOW(IHID,IOUT)
DIM TERR(IOUT)

DEF DSER()
  SOUT="INPUTS," + STR(IIN) + ","
  SOUT=SOUT+"HIDDEN," + STR(IHID) + ","
  SOUT=SOUT+"OUTPUTS," + STR(IOUT) + ","  
  SOUT=SOUT+"HHW,"
  FOR J = 0 TO IHID - 1
    FOR K = 0 TO IIN - 1
      SOUT=SOUT+STR(HHW(K,J))+","
    NEXT K
  NEXT J
  SOUT=SOUT+"HIDDENBIASES,"
  FOR J = 0 TO IHID - 1
    SOUT=SOUT+STR(HHLBIAS(J))+","
  NEXT J
  SOUT=SOUT+"OOW,"
  FOR J = 0 TO IOUT - 1
    FOR K = 0 TO IHID - 1 
      SOUT=SOUT+STR(OOW(K,J))+","
    NEXT K
  NEXT J
  SOUT=SOUT+"OUTPUTBIASES,"
  FOR J = 0 TO IOUT - 1
      SOUT=SOUT+STR(OOLBIAS(J))+"," 
  NEXT J
  RETURN SOUT
ENDDEF
DEF SIGMOID(X) 
  RETURN 1.0 / (1.0 + EXP(-X))
ENDDEF
DEF DSIGMOID(X) 
  RETURN X * (1.0 - X)  
ENDDEF
DEF SKIPTOLINE(X)    
  IF X > 0 THEN    
    RESETFPOS()
    FOR Z = 0 TO X - 1
      TMPLINE=READLINE()
    NEXT Z
  ENDIF 
ENDDEF
FOR I = 0 TO IIN - 1 
  FOR J = 0 TO IHID - 1
    HHW(I,J) = RND
  NEXT J
NEXT I
FOR I = 0 TO IHID - 1
  HHLBIAS(I) = RND
  FOR J = 0 TO IOUT - 1
    OOW(I,J) = RND
  NEXT J
NEXT I
FOR I = 0 TO IOUT - 1
  OOLBIAS(I) = RND
NEXT I
FSIZE=DOWNLOAD(FFP)  
IF FSIZE <= 0 THEN   
  EXIT
ENDIF
FOR I = 0 TO IEPO - 1
  TCNT = 0
  RESETFPOS()
  LLINE = ""

  IF SAT > 0 THEN 
    SKIPTOLINE(SAT)
  ENDIF   
  FOR J = 0 TO IOUT - 1
    TERR(J) = 0.0
  NEXT J

  WHILE TRUE
      SLINE=READLINE()     

      IF LCT > 0 AND TCNT >= LCT THEN
        EXIT
      ENDIF
      IF SLINE = "" THEN         
        EXIT
      ENDIF

      CLEAR(LNLS) 
      LNLS=CSV2LIST(SLINE)
       
      FOR K = 0 TO IIN - 1
        TTI(K) = VAL(GET(LNLS,K))         
      NEXT K
      FOR K = 0 TO IOUT - 1
        TTO(K) = VAL(GET(LNLS,IIN+K))       
      NEXT K  

      FOR J = 0 TO IHID - 1
        ACTIVATION = HHLBIAS(J)
        FOR K = 0 TO IIN - 1 
          ACTIVATION = ACTIVATION + (TTI(K) * HHW(K,J) )
        NEXT K
        HHL(J) = SIGMOID(ACTIVATION)
      NEXT J
      FOR J = 0 TO IOUT - 1
        ACTIVATION = OOLBIAS(J)
        FOR K = 0 TO IHID - 1
          ACTIVATION = ACTIVATION + (HHL(K) * OOW(K,J))
        NEXT K
        OOL(J) = SIGMOID(ACTIVATION)
      NEXT J 
      DIM DELTAOUTPUT(IOUT) 
      FOR J = 0 TO IOUT - 1
        ERROROUTPUT = TTO(J) - OOL(J)
        DELTAOUTPUT(J) = ERROROUTPUT * DSIGMOID(OOL(J))        
        TERR(J) = TERR(J) + ABS(ERROROUTPUT)
      NEXT J
      DIM DELTAHIDDEN(IHID)
      FOR J = 0 TO IHID - 1
        ERRORHIDDEN = 0.0f
        FOR K = 0 TO IOUT -1
          ERRORHIDDEN = DELTAOUTPUT(K) * OOW(J,K)
        NEXT K
        DELTAHIDDEN(J) = ERRORHIDDEN * DSIGMOID(HHL(J))
      NEXT J
      FOR J = 0 TO IOUT - 1
        OOLBIAS(J) = OOLBIAS(J) + (DELTAOUTPUT(J) * LRATE)
        FOR K = 0 TO IHID -1 
          OOW(K,J) = OOW(K,J) + (HHL(K) * DELTAOUTPUT(J) * LRATE)
        NEXT K
      NEXT J
      FOR J = 0 TO IHID - 1
        HHLBIAS(J) = HHLBIAS(J) + (DELTAHIDDEN(J) * LRATE)
        FOR K = 0 TO IIN -1
          HHW(K,J) = HHW(K,J) + (TTI(K) * DELTAHIDDEN(J) * LRATE)
        NEXT K
      NEXT J 
    TCNT = TCNT + 1 
  WEND   

  AERR = 0.0
  FOR J = 0 TO IOUT - 1
    AERR = AERR + (TERR(J) / FSIZE)
  NEXT J
  AERR = AERR / IOUT
NEXT I

SOUT=DSER()
OUTPUTPAYLOAD=FFP+",ERROR,"+STR(AERR)+","+SOUT

