OUTPUTPAYLOAD="" 
CUR_STRING = ""
TCHUNK = LEFT(INPUTPAYLOAD,30)
TDATA = MID(INPUTPAYLOAD,31,LEN(INPUTPAYLOAD)-30-2)
IF LEN(TDATA) <= 0 THEN EXIT
IF WRITE(TCHUNK,B64D(TDATA)) = 1 THEN
OUTPUTPAYLOAD = FMD5(TCHUNK)