OUTPUTPAYLOAD="" 
CUR_STRING = ""
TCHUNK = LEFT(INPUTPAYLOAD,25)
TDATA = MID(INPUTPAYLOAD,26,LEN(INPUTPAYLOAD)-25-2)
IF LEN(TDATA) <= 0 THEN EXIT
IF WRITE(TCHUNK,B64D(TDATA)) = 1 THEN
OUTPUTPAYLOAD = FMD5(TCHUNK)