OUTPUTPAYLOAD="" 
CUR_STRING = ""
'CHUNKNAME IS CONSTANT 30B
TCHUNK = LEFT(INPUTPAYLOAD,30)
'DATA IS WHATS LEFT
TDATA = MID(INPUTPAYLOAD,31,LEN(INPUTPAYLOAD)-30-2)
IF LEN(TDATA) <= 0 THEN EXIT
IF WRITE(TCHUNK,TDATA) = 1 THEN
OUTPUTPAYLOAD = FMD5(TCHUNK)