AMTMAX=10000
LAL=LIST()   
DEF TOK(GDZIE, TO_SPLIT )   
CUR_STRING=""
SLEN=LEN(TO_SPLIT)-1
FOR ICT=0 TO SLEN
CHARV=MID(TO_SPLIT,ICT,1)
IF CHARV <> "," THEN 
CUR_STRING=CUR_STRING+CHARV 
ELSE  
PUSH(GDZIE,CUR_STRING)
CUR_STRING="" 
ENDIF
NEXT ICT 
ENDDEF
TOK(LAL,INPUTPAYLOAD)
AMT=GET(LAL,0)
BAL=GET(LAL,1) 
REC=GET(LAL,2) 

IF LEN(REC) <=0 THEN EXIT
IF VAL(AMT) < 0 THEN EXIT
IF VAL(AMT) = 0 THEN EXIT
IF VAL(BAL)-VAL(AMT) < 0 THEN EXIT
IF VAL(AMT) > AMTMAX THEN EXIT

OUTPUTPAYLOAD="OK"
