REM SHA1 HASH GENERATOR
DEF TOKENIZE( TO_SPLIT , ARG)  
IDX = 0 
CUR_STRING = ""
FOR ICT = 0 TO LEN(TO_SPLIT)-1
  LET CHARV = MID( TO_SPLIT, ICT , 1 )
  IF CHARV <> "," THEN 
    CUR_STRING = CUR_STRING + CHARV 
  ELSE  
    IF IDX = ARG THEN
      RETURN CUR_STRING
    ENDIF
    CUR_STRING = "" 
    IDX = IDX + 1
  ENDIF
NEXT ICT 
ENDDEF  
PLAINTEXT = TOKENIZE(INPUTPAYLOAD,0) 
HASH = SHA1(PLAINTEXT)
OUTPUTPAYLOAD=HASH 