'WATERMELON
'HOUR,TEMPERATURE,
LL=LIST()
LL=CSV2LIST(INPUTPAYLOAD)

WATER=0
HR=VAL(GET(LL,0))
TEMP=VAL(GET(LL,1))

WATER=0
IF HR = 5 OR HR = 11 OR HR = 13 OR HR = 15 OR HR = 22 THEN
WATER=300000
ENDIF

OUTPUTPAYLOAD=STR(WATER)