'Whale daily average
'INPUTPAYLOAD="PocNetGroupMiners00000000000000000000001,083AF25746D8,202372,6,"
TUCURSOR = 0
VTOTAL = 0
VTOTALCOUNT = 0
LISTA = LIST()   
'''''''''''''''''''''''''''''''''''
DEF TOKENIZE(GDZIE, TO_SPLIT )   
  CUR_STRING = ""
  FOR ICT = 0 TO LEN(TO_SPLIT)-1
    LET CHARV = MID( TO_SPLIT, ICT , 1 )
    IF CHARV <> "," THEN 
      CUR_STRING = CUR_STRING + CHARV 
    ELSE  
      PUSH(GDZIE,CUR_STRING)
      CUR_STRING = "" 
    ENDIF
  NEXT ICT 
ENDDEF 
''''''''''''''''''''''''''''''''''' 
DEF READ_UNTIL(ASC_CHARACTER)
STRO=""
WHILE TRUE
    NEWS = READ(TUCURSOR,1)
    '' END
    IF NEWS = "" THEN
    RETURN ""
    ENDIF
    '' NEW LINE
    IF ASC(NEWS) = ASC_CHARACTER THEN
        TUCURSOR = TUCURSOR + 1
        RETURN STRO
    ELSE 
        STRO = STRO + NEWS
    ENDIF
    TUCURSOR=TUCURSOR+1
WEND  
ENDDEF
'''''''''''''''''''''''''''''''''''  
PAYLOAD=LIST() 
TOKENIZE(PAYLOAD, INPUTPAYLOAD) 
VUSER=GET(PAYLOAD,0)
VSENSOR=GET(PAYLOAD,1)
VDATE=GET(PAYLOAD,2)
VIDX=GET(PAYLOAD,3)
  
INFILE = VUSER+"POOLT"+VSENSOR+VDATE
OUTFILE="POOLT"+VSENSOR+"AVGD"
 
GETIT = DOWNLOAD(INFILE)
PRINT "DOWNLOADED ",GETIT," BYTES"; 
IF GETIT = 0 THEN 
PRINT "ERROR DOWNLOADING";
EXIT
ENDIF

WHILE TRUE
 LINE = READ_UNTIL(10)
 IF LINE<>"" THEN
  LINE=LINE+","
  PRINT LINE;

  CLEAR(LISTA)
  TOKENIZE(LISTA, LINE)  
  VAR RAWVALUE = GET(LISTA,VAL(VIDX))   
  VTOTAL = VTOTAL+VAL(RAWVALUE)
  VTOTALCOUNT = VTOTALCOUNT + 1

 ELSE
  EXIT
 ENDIF
WEND

'' Calc avg
VRESULT = VTOTAL/VTOTALCOUNT
OUTPUTPAYLOAD=VDATE+","+STR(VRESULT)+CHR(10)

'' Append outpufile
WRITE(OUTFILE,OUTPUTPAYLOAD,TRUE)
PRINT "DONE";


