'SIMPLE WIDGET GENERATOR STORES JSON AS TELEMETRY
'PROVIDE NEW LINES WITH DOUBLE ESCAPE \\n
'INPUTPAYLOAD="FNAME,WNAME,WDESC,WTEXT,#00FF00,https://gridshell.net/,"
SVERSION="1.0"
PRINT "STARTING ",SVERSION," NOW";
DEF PTOKENIZER( TO_SPLIT , ARG)  
IDX = 0 
CUR_STRING = ""
FOR ICT = 0 TO LEN(TO_SPLIT)-1
  LET CHARV = MID( TO_SPLIT, ICT , 1 )
  IF CHARV <> "," THEN 
    CUR_STRING = CUR_STRING + CHARV 
  ELSE  
    IF IDX = ARG THEN
      RETURN CUR_STRING
    ENDIF
    CUR_STRING = "" 
    IDX = IDX + 1
  ENDIF
NEXT ICT 
ENDDEF  
TFNAME=PTOKENIZER(INPUTPAYLOAD,0)
TNAME=PTOKENIZER(INPUTPAYLOAD,1)
TDESC=PTOKENIZER(INPUTPAYLOAD,2)  
TTXT=PTOKENIZER(INPUTPAYLOAD,3)
TCOLOR=PTOKENIZER(INPUTPAYLOAD,4)
TURL=PTOKENIZER(INPUTPAYLOAD,5)
JSONPAYLOAD="{"+CHR(34)+"name"+CHR(34)+":"+CHR(34)+TNAME+CHR(34)+","+CHR(34)+"description"+CHR(34)+":"+CHR(34)+TDESC+CHR(34)+","+CHR(34)+"data"+CHR(34)+":{"+CHR(34)+"content_url"+CHR(34)+":"+CHR(34)+TURL+CHR(34)+"},"+CHR(34)+"layouts"+CHR(34)+":{"+CHR(34)+"t0"+CHR(34)+":{"+CHR(34)+"size"+CHR(34)+":"+CHR(34)+"small"+CHR(34)+","+CHR(34)+"styles"+CHR(34)+":{"+CHR(34)+"colors"+CHR(34)+":{"+CHR(34)+"cpurpl"+CHR(34)+":{"+CHR(34)+"color"+CHR(34)+":"+CHR(34)+TCOLOR+CHR(34)+"}}},"+CHR(34)+"layers"+CHR(34)+":[{"+CHR(34)+"rows"+CHR(34)+":[{"+CHR(34)+"height"+CHR(34)+":12,"+CHR(34)+"cells"+CHR(34)+":[{"+CHR(34)+"width"+CHR(34)+":12,"+CHR(34)+"background_color_style"+CHR(34)+":"+CHR(34)+"cpurpl"+CHR(34)+","+CHR(34)+"text"+CHR(34)+":{"+CHR(34)+"string"+CHR(34)+":"+CHR(34)+TTXT+CHR(34)+"}}]}]}]}}}"
WRITE(TFNAME,JSONPAYLOAD,FALSE) 
OUTPUTPAYLOAD=SHA1(JSONPAYLOAD)